columns:
  - 'CMIULOCAL'
  - 'CMNOMLOCAL'
  - 'CMIUUPLA'
  - 'CMNOMUPLA'
  - 'CMIUSCAT'
  - 'CMNOMSCAT'
  - 'CMMES'
  - 'CMHP18CONT'
  - 'CMHP19CONT'
  - 'CMHP20CONT'
  - 'CMHP21CONT'
  - 'CMHP22CONT'
  - 'CMHPVAR'
  - 'CMHPTOTAL'
  - 'CMHB18CONT'
  - 'CMHB19CONT'
  - 'CMHB20CONT'
  - 'CMHB21CONT'
  - 'CMHB22CONT'
  - 'CMHBVAR'
  - 'CMHBTOTAL'
  - 'CMHA18CONT'
  - 'CMHA19CONT'
  - 'CMHA20CONT'
  - 'CMHA21CONT'
  - 'CMHA22CONT'
  - 'CMHAVAR'
  - 'CMHATOTAL'
  - 'CMHM18CONT'
  - 'CMHM19CONT'
  - 'CMHM20CONT'
  - 'CMHM21CONT'
  - 'CMHM22CONT'
  - 'CMHMVAR'
  - 'CMHMTOTAL'
  - 'CMHCE18CONT'
  - 'CMHCE19CONT'
  - 'CMHCE20CONT'
  - 'CMHCE21CONT'
  - 'CMHCE22CONT'
  - 'CMHCEVAR'
  - 'CMHCETOTAL'
  - 'SHAPE.AREA'
  - 'SHAPE.LEN'
  - 'geometry'
  